### ISSUE TITLE
Fix deprecations: and_return { } -> and_return(value)

### ISSUE THREAD

**Issue by dsandstrom** [sgruhier/foundation_rails_helper#70]
`and_return { value }` is deprecated. Use `and_return(value)` or an implementation block without `and_return` instead. Called from /home/me/Projects/gems/foundation_rails_helper/spec/support/mock_rails.rb:133:in `mock_everything'.

`and_return` without arguments is deprecated. Remove the `and_return`. Called from /home/me/Projects/gems/foundation_rails_helper/spec/support/mock_rails.rb:114:in `mock_everything'.

**Comment by dsandstrom** [comment]
Closed by #80
